### ISSUE TITLE
FFI assumes the global scope is available on `window`

### ISSUE THREAD

**Issue by bodil** [CapillarySoftware/purescript-timers#2]
Timeout functions are invoked as `window.setTimeout` rather than just `setTimeout`, which won't work unless you're running in an actual browser with a `window` available. This is a bit of a shame as I like to run my test suites with timeouts in a Node environment...

**Comment by FrigoEU** [comment]
This seems to break when building with optimizations (-O).

**Comment by Fresheyeball** [comment]
@FrigoEU can you be more specific? What seems to break? Can you open a new issue that describes your problem?
