### ISSUE TITLE
Compiling with Optimizations

### ISSUE THREAD

**Issue by FrigoEU** [CapillarySoftware/purescript-timers#6]
Hey, using version 0.0.8, compiling the simplest example possible:

    import Control.Timer                                                                                  
    import Debug.Trace                                                                                    
                                                                                                      
    main = do                                                                                             
      interval 1000 $ trace "foo"

I'm getting an error when compiling with optimizations. The error I'm getting is this:

    Uncaught ReferenceError: globalEnv is not defined

When compiling without -O, everything works.

**Comment by Fresheyeball** [comment]
Are you sure its this project causing the error? I `grep`ed for `globalEnv` in `purescript-timers`, `purescript-oo-ffi` and `purescript-context` and I am not finding anything. Are you running in Node or the Browser? What other packages are you using?

**Comment by FrigoEU** [comment]
Hmm, this seems to indeed be a problem with the 0.0.8 version of the library. I updated it to aef2bcf4f56a9d440cf81a83ff6485874d30fb8d in my bower.json file and it works. 

0.0.8 is the version I get when just requiring "*" in my bower.json, so a version update might be useful?

**Comment by Fresheyeball** [comment]
I just updated bower to version 0.0.9 based on current master, please test.

**Comment by FrigoEU** [comment]
Works!

**Comment by Fresheyeball** [comment]
Vunderbar!
