### ISSUE TITLE
support PureScript 0.7.x

### ISSUE THREAD

**Issue by michaelficarra** [CapillarySoftware/purescript-timers#7]
I'm going to have to drop this dependency from purescript-signal until this issue is resolved.

**Comment by Fresheyeball** [comment]
Makes sense. I am getting crushed by a release cycle at work, and it looks like most of my packages need a total re-write for 0.7.x. Dropping the dependency sounds like the best option in the short term.

**Comment by Fresheyeball** [comment]
This is currently resolved.
